USE [master]
GO

/****** Object:  Database [DataStotageAndExchangeDB]    Script Date: 05.07.2021 12:56:49 ******/
CREATE DATABASE [DataStotageAndExchangeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataStotageAndExchange_var4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DataStotageAndExchange_var4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DataStotageAndExchange_var4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DataStotageAndExchange_var4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataStotageAndExchangeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET  MULTI_USER 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DataStotageAndExchangeDB] SET  READ_WRITE 
GO


